#!/bin/sh

host="https://us-east.manta.joyent.com"
latest_path="$(curl -sk $host/Joyent_Dev/public/SmartOS/latest)"
version="${latest_path##*/}"
platform_file="platform-$version.tgz"
platform_dir="platform-$version"
platform_url="$host$latest_path/$platform_file"
md5sums_url="$host$latest_path/md5sums.txt"

_check_return(){
	if [ $? -gt 0  ]; then
		printf '%s\n' ' FAILED'
		exit -1
	else
	        printf '%s\n' ' OK'
	fi
}

force="false"
while getopts :f option; do
	case "$option" in
		f)
			force="true"
			;;
		\?)
			printf 'Invalid option: %s\n'  "-$OPTARG" >&2
			exit -1
			;;
	esac
done
shift $((OPTIND-1))

IFS=_ read brand kernel < <(uname -v)
if [ "$kernel" == "$version" ]; then
	printf 'Already on latest version (%s)\n' "$kernel"
	$force ||exit -1
fi

tmp="$(mktemp -d)"
cd "$tmp" ||exit -1

printf '%s' "Downloading latest platform ($platform_file)..."
curl -sk -o "$platform_file" "$platform_url"
_check_return

printf '%s' "Verifying checksum..."
curl -sk "$md5sums_url" \
	|grep "$platform_file" \
	|awk '{print $1}' >expected.md5
openssl md5 "$platform_file" |awk '{print $2}' >actual.md5
cmp -s actual.md5 expected.md5
_check_return

printf '%s' "Extracting latest platform..."
gtar zxf "$platform_file"
_check_return

printf '%s' "Marking release version..."
echo $version >"$platform_dir/VERSION"
_check_return

printf '%s' "Checking current boot device..."
if [ -z "$1" ]; then
	removables="$(disklist -r)"
	printf ' detected %s\n' "${removables[@]}"
	if [ "${#removables[@]}" -gt 1 ]; then
		echo
		echo "Error: more than one removable device detected."
		echo "Specify correct device on the command line."
		exit -1
	fi
	usb="/dev/dsk/${removables[0]}p1"
else
	usb="$1"
	printf ' using %s' "$usb"
fi

umount "$usb" 2>/dev/null
mkdir usb
mount -F pcfs -o foldcase "$usb" "$tmp/usb"
if [ $? -gt 0 ]; then
	printf '%s\n' ', mount failed'
	exit -1
else
	printf '%s\n' ', mounted'
fi

if [ ! -d usb/platform ]; then
	printf '%s\n" ', missing platform dir'
	exit -1
else
	printf '%s\n' ', OK'
fi

printf '%s' "Updating platform on boot device..."
rsync -a "$platform_dir/" usb/platform.new/
_check_return

printf '%s' "Remounting boot device..."
umount "$usb" 2>/dev/null
mount -F pcfs -o foldcase "$usb" "$tmp/usb"

printf '%s' "Verifying kernel checksum on boot device..."
openssl dgst -sha1 "$platform_dir"/i86pc/kernel/amd64/unix |cut -d ' ' -f 2 >kernel.expected
openssl dgst -sha1 usb/platform.new/i86pc/kernel/amd64/unix |cut -d ' ' -f 2 >kernel.actual
cmp -s kernel.actual kernel.expected
_check_return

printf '%s' "Verifying boot_archive checksum on boot device..."
openssl dgst -sha1 usb/platform.new/i86pc/amd64/boot_archive |cut -d ' ' -f 2 >boot_archive.actual
cmp -s boot_archive.actual usb/platform.new/i86pc/amd64/boot_archive.hash
_check_return

printf '%s' "Activating new platform on $usb..."
rm -rf usb/old
mkdir usb/old
mv usb/platform usb/old && mv usb/platform.new usb/platform
_check_return

printf '%s' "

  Boot device upgraded. To do:

    1) Sanity check the contents of $tmp/usb
    2) umount $usb
    3) reboot

"
